name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      should_fail:
        description: "Forçar falha?"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simular teste
        run: |
            echo "Rodando testes..."

            MSG="${{ github.event.head_commit.message }}${{ github.event.pull_request.title }}"

            if echo "$MSG" | grep -qi "\[fail-ci\]"; then
            echo "❌ Falha forçada via commit"
            exit 1
            fi

            echo "✅ Sucesso"