name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      should_fail:
        description: "Forçar falha?"
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter mensagem do último commit
        id: commit_msg
        run: |
            MSG=$(git log -1 --pretty=%B)
            echo "msg<<EOF" >> $GITHUB_OUTPUT
            echo "$MSG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

      - name: Simular teste
        run: |
            MSG="${{ steps.commit_msg.outputs.msg }}"

            echo "Mensagem do commit:"
            echo "$MSG"

            if echo "$MSG" | grep -qi "\[fail-ci\]"; then
            echo "❌ Falha forçada (commit atual)"
            exit 1
            fi

            echo "✅ Sucesso"